---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
  - name: Start clickhouse service
    become: true
    ansible.builtin.service:
      name: clickhouse-server
      state: restarted

  tasks:
  - name: Instaling Clickhouse
    block:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
        dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
        mode: '0644'
      with_items: "{{ clickhouse_packages }}"
    rescue:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
        dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
        mode: '0644'
  - name: Install clickhouse packages
    become: true
    ansible.builtin.yum:
      name:
      - clickhouse-common-static-{{ clickhouse_version }}.rpm
      - clickhouse-client-{{ clickhouse_version }}.rpm
      - clickhouse-server-{{ clickhouse_version }}.rpm
    notify: Start clickhouse service
  - name: Flush handlers
    ansible.builtin.meta: flush_handlers
  - name: Create database
    ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
    register: create_db
    failed_when: create_db.rc != 0 and create_db.rc !=82
    changed_when: create_db.rc == 0

- name: Lighthouse
  hosts: lighthouse
  gather_facts: false
  remote_user: nightnek
  tags: lighthouse

  handlers:
  - name: Start Lighthouse service
    become: true
    ansible.builtin.systemd:
      daemon_reload: true
      enabled: false
      name: nginx.service
      state: restarted

  tasks:
  - name: Install, configure, and start Lighthouse
    block:
    - name: Pre-install Nginx & Git client
      become: true
      ansible.builtin.yum:
        name: "{{ lighthouse_packages }}"
        update_cache: true

    - name: Clone Lighthouse source code by Git
      become: true
      ansible.builtin.git:
        repo: "{{ lighthouse_code_src }}"
        version: "{{ lighthouse_code_src_version }}"
        dest: "{{ lighthouse_data_dir }}"

    - name: Prepare nginx config
      become: true
      ansible.builtin.template:
        src: "templates/nginx/lighthouse.conf.j2"
        dest: "/etc/nginx/conf.d/{{ lighthouse_nginx_conf }}"
        mode: "0644"
        owner: root
        group: root
      notify: Start Lighthouse service

- name: Vector
  hosts: vector
  gather_facts: false
  remote_user: nightnek
  tags: vector

  handlers:
  - name: Start Vector service
    become: true
    ansible.builtin.systemd:
      daemon_reload: true
      enabled: false
      name: vector.service
      state: restarted

  tasks:
  - name: Install, configure, and start Vector
    block:
    - name: Create vector work directory
      ansible.builtin.file:
        path: "{{ vector_workdir }}"
        state: directory
        mode: "0755"

    - name: Get Vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-{{ vector_os_arch }}-unknown-linux-gnu.tar.gz"
        dest: "{{ vector_workdir }}/vector-{{ vector_version }}-{{ vector_os_arch }}-unknown-linux-gnu.tar.gz"
        mode: "0644"
