#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
- name: night
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIATCa7b5AkkJuPKo9mYUERJ6dsW9l5np2qpirQFQ4y+9 nightnek@Nightneklaptop
